version: '3.8'
services:
  mealapi:
    image: koldynok/mealapi:latest
    container_name: mealapi
    command: uvicorn app.main:app --host=0.0.0.0 --port 80
    ports:
     - "80:80"
    env_file:
       - .env
    volumes:
       - mealapidb:/code/db
   #  networks:
   #     - nginx-proxy-net

    # depends_on:
    #   - db
    # restart: always
    # links:
    #   - "db:database"
    # networks:
    #   - stack
#   db:
#     image: postgres
#     container_name: ${POSTGRES_HOST}
#     ports:
#       - "${POSTGRES_PORT}:5432"
#     env_file:
#       - .env
#     restart: always
#     networks:
#       - stack
# networks:
#   nginx-proxy-net:
    # external: true

volumes:
  mealapidb:
